import type { Metadata } from 'next';
import WaveDivider from '@/components/WaveDivider';

export const metadata: Metadata = {
  title: 'Privacy Policy | Sophos Technology Consultancy LLC',
};

const containerStyle = {
  maxWidth: '1080px',
  width: '80%' as const,
  margin: '0 auto',
};

const h3Style = {
  fontFamily: 'var(--font-roboto), Roboto, Helvetica, Arial, sans-serif',
  fontSize: '22px',
  fontWeight: 700,
  color: '#121212',
  marginTop: '30px',
  marginBottom: '15px',
};

const pStyle = {
  fontSize: '16px',
  fontWeight: 400 as const,
  lineHeight: '28.8px',
  color: '#666666',
  marginBottom: '15px',
};

export default function PrivacyPolicyPage() {
  return (
    <>
      <section
        style={{
          background: 'linear-gradient(1deg, rgb(142, 235, 226) 0%, rgb(37, 232, 157) 100%)',
          padding: '43px 0 58px 0',
          position: 'relative',
        }}
      >
        <div className="r-container" style={{ ...containerStyle, textAlign: 'center' as const }}>
          <h2
            style={{
              fontFamily: 'var(--font-roboto), Roboto, Helvetica, Arial, sans-serif',
              fontSize: '45px',
              fontWeight: 700,
              color: '#121212',
              textTransform: 'uppercase' as const,
              letterSpacing: '1px',
            }}
          >
            Privacy Policy
          </h2>
        </div>
        <WaveDivider position="bottom" shape="zigzag" fill="#ffffff" height={35} />
      </section>

      <section style={{ padding: '54px 0' }}>
        <div className="r-container" style={containerStyle}>
          <p style={pStyle}>
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You. We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
          </p>

          <h3 style={h3Style}>Interpretation and Definitions</h3>
          <p style={pStyle}>
            The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
          </p>
          <p style={pStyle}><strong>For the purposes of this Privacy Policy:</strong></p>
          <ul style={{ ...pStyle, paddingLeft: '20px' }}>
            <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
            <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
            <li><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to sophostc.com.</li>
            <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
            <li><strong>Country</strong> refers to: United Arab Emirates.</li>
            <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
            <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
            <li><strong>Service</strong> refers to the Website.</li>
            <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
            <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
            <li><strong>Website</strong> refers to sophostc.com, accessible from https://sophostc.com</li>
            <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
          </ul>

          <h3 style={h3Style}>Collecting and Using Your Personal Data</h3>
          <h4 style={{ ...h3Style, fontSize: '18px', marginTop: '20px' }}>Personal Data</h4>
          <p style={pStyle}>
            While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to: email address, first name and last name, phone number, address, state, province, ZIP/postal code, city, and usage data.
          </p>

          <h4 style={{ ...h3Style, fontSize: '18px', marginTop: '20px' }}>Usage Data</h4>
          <p style={pStyle}>
            Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device&apos;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
          </p>
          <p style={pStyle}>
            When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
          </p>

          <h4 style={{ ...h3Style, fontSize: '18px', marginTop: '20px' }}>Tracking Technologies and Cookies</h4>
          <p style={pStyle}>
            We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.
          </p>
          <p style={pStyle}>
            Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. We use both Session and Persistent Cookies for the purposes set out below:
          </p>
          <ul style={{ ...pStyle, paddingLeft: '20px' }}>
            <li><strong>Necessary / Essential Cookies</strong> — These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features.</li>
            <li><strong>Cookies Policy / Notice Acceptance Cookies</strong> — These Cookies identify if users have accepted the use of cookies on the Website.</li>
            <li><strong>Functionality Cookies</strong> — These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference.</li>
          </ul>

          <h3 style={h3Style}>Use of Your Personal Data</h3>
          <p style={pStyle}>The Company may use Personal Data for the following purposes:</p>
          <ul style={{ ...pStyle, paddingLeft: '20px' }}>
            <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
            <li>To manage Your Account: to manage Your registration as a user of the Service.</li>
            <li>For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
            <li>To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
            <li>To provide You with news, special offers and general information about other goods, services and events which we offer.</li>
            <li>To manage Your requests to Us.</li>
            <li>For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.</li>
            <li>For other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service.</li>
          </ul>

          <p style={pStyle}>We may share Your personal information in the following situations:</p>
          <ul style={{ ...pStyle, paddingLeft: '20px' }}>
            <li><strong>With Service Providers</strong> to monitor and analyze the use of our Service, to contact You.</li>
            <li><strong>For business transfers</strong> in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition.</li>
            <li><strong>With Affiliates</strong>, in which case we will require those affiliates to honor this Privacy Policy.</li>
            <li><strong>With business partners</strong> to offer You certain products, services or promotions.</li>
            <li><strong>With other users</strong> when You share personal information or otherwise interact in the public areas with other users.</li>
            <li><strong>With Your consent</strong> for any other purpose.</li>
          </ul>

          <h3 style={h3Style}>Retention of Your Personal Data</h3>
          <p style={pStyle}>
            The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.
          </p>

          <h3 style={h3Style}>Transfer of Your Personal Data</h3>
          <p style={pStyle}>
            Your information, including Personal Data, is processed at the Company&apos;s operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.
          </p>
          <p style={pStyle}>
            The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.
          </p>

          <h3 style={h3Style}>Delete Your Personal Data</h3>
          <p style={pStyle}>
            You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. Our Service may give You the ability to delete certain information about You from within the Service. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.
          </p>

          <h3 style={h3Style}>Disclosure of Your Personal Data</h3>
          <p style={pStyle}>
            If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
          </p>
          <p style={pStyle}>
            Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
          </p>
          <p style={pStyle}>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
          <ul style={{ ...pStyle, paddingLeft: '20px' }}>
            <li>Comply with a legal obligation</li>
            <li>Protect and defend the rights or property of the Company</li>
            <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
            <li>Protect the personal safety of Users of the Service or the public</li>
            <li>Protect against legal liability</li>
          </ul>

          <h3 style={h3Style}>Security of Your Personal Data</h3>
          <p style={pStyle}>
            The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
          </p>

          <h3 style={h3Style}>Children&apos;s Privacy</h3>
          <p style={pStyle}>
            Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.
          </p>

          <h3 style={h3Style}>Links to Other Websites</h3>
          <p style={pStyle}>
            Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party&apos;s site. We strongly advise You to review the Privacy Policy of every site You visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
          </p>

          <h3 style={h3Style}>Changes to this Privacy Policy</h3>
          <p style={pStyle}>
            We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.
          </p>

          <h3 style={h3Style}>Contact Us</h3>
          <p style={pStyle}>If you have any questions about this Privacy Policy, You can contact us:</p>
          <ul style={{ ...pStyle, paddingLeft: '20px' }}>
            <li>By email: info@sophostc.com</li>
            <li>By visiting our <a href="/contact" style={{ color: '#2ea3f2' }}>contact page</a></li>
          </ul>
        </div>
      </section>
    </>
  );
}
